services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:$VERSION
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      VAULT_TOKEN: ${VAULT_TOKEN} 
      VIRTUAL_HOST: "backend"
      VIRTUAL_PORT: "8080"
      REPORT_PATH: /var/sausage-store/reports
      LOG_PATH: /var/sausage-store/logs
    restart: always
    networks:
      - sausage-store
  backend-report:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend-report:$VERSION
    container_name: sausage-backend-report
    environment:
      DB: ${DB}
      PORT: ${PORT}
    ports:
      - "8080:8080"
    restart: always
    networks:
      - sausage-store
  frontend:
    image: $CI_REGISTRY_IMAGE/sausage-frontend:$VERSION
    container_name: sausage-frontend
    environment:
      DEFAULT_HOST: "backend"
    ports:
      - "80:80"
    restart: always
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - sausage-store

networks:
  sausage-store: