stages:
  - build
  - test
  - notify

build-backend-code-job:
  stage: build
  cache:
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  only:
    changes:
    - backend/**/*
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

semgrep-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  needs:
    - build-backend-code-job

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd backend
    - mvn clean verify sonar:sonar -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK} -Dsonar.login=${SONAR_LOGIN} -Dsonar.projectName=${SONAR_PROJECT_KEY} -Dsonar.qualitygate.wait=true
  allow_failure: true
  needs:
    - build-backend-code-job

telegram-notification-backend:
  stage: notify
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
      changes: 
        - backend/**/*
  script:
    - >
      curl -X POST -H "Content-type: application/json" --data '{"chat_id":"-1002558070233", "text":"'"${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_SHA}/download?job=${CI_JOB_NAME}"'"}' https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage
  needs:
    - build-backend-code-job
